### ISSUE TITLE
不应该写else，否则第一次调用未返回实例

### ISSUE THREAD

**Issue by HosheaGan** [liuzhenya1996/ts-study-notes#1]
https://github.com/liuzhenya1996/ts-study-notes/blob/262f0ba414a62e8680f88edbcfb5c1934e984c9e/ts/Class%E7%B1%BB.ts#L104

**Comment by liuzhenya1996** [comment]
修复：https://github.com/liuzhenya1996/ts-study-notes/commit/7dab1a960246fce52ad00cee8f35b58d207df63f
